const jsonContent = (schema: Record<string, unknown>) => ({
  "application/json": {
    schema,
  },
});

const successSchema = (dataSchema: Record<string, unknown>, metaSchema?: Record<string, unknown>) => ({
  type: "object",
  required: ["success", "message", "data"],
  properties: {
    success: { type: "boolean", enum: [true] },
    message: { type: "string" },
    data: dataSchema,
    meta: metaSchema ?? { type: "object", nullable: true },
  },
});

const successResponse = (description: string, dataSchema: Record<string, unknown>, metaSchema?: Record<string, unknown>) => ({
  description,
  content: jsonContent(successSchema(dataSchema, metaSchema)),
});

const errorResponse = (description: string) => ({
  description,
  content: jsonContent({ $ref: "#/components/schemas/ApiError" }),
});

const ref = (name: string) => ({
  $ref: `#/components/schemas/${name}`,
});

export function getOpenApiDocument() {
  return {
    openapi: "3.0.3",
    info: {
      title: "NSDC Training Management Portal API",
      version: "0.6.0",
      description:
        "Authentication, master data, candidate intake, sync processing, batch operations, enrollment management, and attendance ingestion for the NSDC training management platform.",
    },
    servers: [{ url: "/api/v1" }],
    tags: [
      { name: "Auth", description: "Authentication, session, and password reset endpoints" },
      { name: "Admin Users", description: "Scoped internal user management endpoints" },
      { name: "Masters", description: "Program, sector, scheme, course, and training-center master data endpoints" },
      { name: "Candidates", description: "Candidate CRUD, SIDH linking, import staging, and sync queueing endpoints" },
      { name: "Batches", description: "Batch CRUD, candidate alignment, SIDH batch sync, and enrollment sync endpoints" },
      { name: "Attendance", description: "Attendance import staging, commit, and summary endpoints" },
      { name: "Sync Jobs", description: "Operator-facing sync queue visibility and retry endpoints" },
      { name: "Reference Data", description: "Normalized candidate dropdown and enum endpoints" },
      { name: "Health", description: "Service liveness and readiness checks" },
      { name: "Docs", description: "OpenAPI and API documentation endpoints" },
    ],
    components: {
      securitySchemes: {
        cookieAuth: {
          type: "apiKey",
          in: "cookie",
          name: "nsdc_access_token",
          description: "HttpOnly session cookie issued after successful login",
        },
      },
      parameters: {
        UserId: {
          name: "userId",
          in: "path",
          required: true,
          schema: { type: "string" },
          description: "Internal NSDC user identifier",
          example: "usr_0a1b2c3d4e5f6g7h",
        },
        Page: {
          name: "page",
          in: "query",
          required: false,
          schema: { type: "integer", minimum: 1, default: 1 },
          description: "1-based page number",
        },
        PageSize: {
          name: "pageSize",
          in: "query",
          required: false,
          schema: { type: "integer", minimum: 1, maximum: 100, default: 20 },
          description: "Number of rows per page",
        },
        CandidateId: {
          name: "candidateId",
          in: "path",
          required: true,
          schema: { type: "string" },
          description: "Internal candidate identifier",
          example: "cand_0a1b2c3d4e5f6g7h",
        },
        ImportJobId: {
          name: "jobId",
          in: "path",
          required: true,
          schema: { type: "string" },
          description: "Candidate import job identifier",
          example: "imp_0a1b2c3d4e5f6g7h",
        },
        BatchId: {
          name: "batchId",
          in: "path",
          required: true,
          schema: { type: "string" },
          description: "Internal batch identifier",
          example: "bat_0a1b2c3d4e5f6g7h",
        },
        AttendanceImportJobId: {
          name: "jobId",
          in: "path",
          required: true,
          schema: { type: "string" },
          description: "Attendance import job identifier",
          example: "attup_0a1b2c3d4e5f6g7h",
        },
        SyncJobId: {
          name: "jobId",
          in: "path",
          required: true,
          schema: { type: "string" },
          description: "Sync job identifier",
          example: "sync_0a1b2c3d4e5f6g7h",
        },
      },
      schemas: {
        ApiErrorDetail: {
          type: "object",
          required: ["message"],
          properties: {
            field: { type: "string", nullable: true },
            message: { type: "string" },
          },
        },
        ApiError: {
          type: "object",
          required: ["success", "message", "errorCode", "errors"],
          properties: {
            success: { type: "boolean", enum: [false] },
            message: { type: "string" },
            errorCode: { type: "string" },
            errors: {
              type: "array",
              items: ref("ApiErrorDetail"),
            },
          },
        },
        AuthPortal: {
          type: "string",
          enum: ["admin", "training_partner"],
        },
        RoleKey: {
          type: "string",
          enum: [
            "platform_admin",
            "training_partner_admin",
            "center_manager",
            "trainer_data_entry",
            "auditor_viewer",
          ],
        },
        PermissionKey: {
          type: "string",
          enum: [
            "auth:login",
            "auth:logout",
            "auth:me",
            "users:read",
            "users:write",
            "users:assign_roles",
            "users:assign_centers",
            "masters:read",
            "masters:write",
            "centers:read",
            "centers:write",
            "candidates:read",
            "candidates:write",
            "batches:read",
            "batches:write",
            "batches:sync",
            "attendance:read",
            "attendance:write",
            "sync:read",
            "sync:write",
            "reference-data:read",
            "audit:read",
          ],
        },
        User: {
          type: "object",
          required: [
            "id",
            "name",
            "email",
            "mobileNumber",
            "roles",
            "role",
            "centerIds",
            "status",
            "mustChangePassword",
            "lastLoginAt",
          ],
          properties: {
            id: { type: "string", example: "usr_0a1b2c3d4e5f6g7h" },
            name: { type: "string", example: "Platform Admin" },
            email: { type: "string", format: "email", example: "admin@example.com" },
            mobileNumber: { type: "string", nullable: true, example: "9876543210" },
            roles: { type: "array", items: ref("RoleKey") },
            role: ref("RoleKey"),
            centerIds: { type: "array", items: { type: "string" } },
            status: { type: "string", enum: ["active", "inactive"] },
            mustChangePassword: { type: "boolean" },
            lastLoginAt: { type: "string", nullable: true, format: "date-time" },
          },
        },
        LoginRequest: {
          type: "object",
          required: ["email", "password"],
          properties: {
            email: { type: "string", format: "email" },
            password: { type: "string", format: "password", minLength: 8 },
            portal: ref("AuthPortal"),
          },
        },
        LoginResponseData: {
          type: "object",
          required: ["user", "accessToken", "permissions", "redirectPath"],
          properties: {
            user: ref("User"),
            accessToken: { type: "string" },
            permissions: { type: "array", items: ref("PermissionKey") },
            redirectPath: { type: "string", example: "/admin/dashboard" },
          },
        },
        AuthMeData: {
          type: "object",
          required: ["user", "permissions"],
          properties: {
            user: ref("User"),
            permissions: { type: "array", items: ref("PermissionKey") },
          },
        },
        ForgotPasswordRequest: {
          type: "object",
          required: ["email", "portal"],
          properties: {
            email: { type: "string", format: "email" },
            portal: ref("AuthPortal"),
          },
        },
        ForgotPasswordResetRequest: {
          type: "object",
          required: ["email", "portal", "otp", "newPassword"],
          properties: {
            email: { type: "string", format: "email" },
            portal: ref("AuthPortal"),
            otp: { type: "string", pattern: "^[0-9]{6}$", example: "123456" },
            newPassword: { type: "string", format: "password", minLength: 8 },
          },
        },
        MessageData: {
          type: "object",
          required: ["message"],
          properties: {
            message: { type: "string" },
          },
        },
        PasswordResetResponseData: {
          type: "object",
          required: ["message", "redirectPath"],
          properties: {
            message: { type: "string" },
            redirectPath: { type: "string", example: "/admin/login" },
          },
        },
        PaginationMeta: {
          type: "object",
          required: ["page", "pageSize", "total"],
          properties: {
            page: { type: "integer", minimum: 1 },
            pageSize: { type: "integer", minimum: 1, maximum: 100 },
            total: { type: "integer", minimum: 0 },
          },
        },
        CreateUserRequest: {
          type: "object",
          required: ["name", "email", "temporaryPassword"],
          properties: {
            name: { type: "string", minLength: 2, maxLength: 120 },
            email: { type: "string", format: "email" },
            mobileNumber: { type: "string", pattern: "^[0-9]{10}$" },
            role: ref("RoleKey"),
            roles: { type: "array", items: ref("RoleKey") },
            centerIds: { type: "array", items: { type: "string" } },
            temporaryPassword: { type: "string", format: "password", minLength: 8 },
          },
        },
        UpdateUserRequest: {
          type: "object",
          properties: {
            name: { type: "string", minLength: 2, maxLength: 120 },
            email: { type: "string", format: "email" },
            mobileNumber: { type: "string", pattern: "^[0-9]{10}$" },
            status: { type: "string", enum: ["active", "inactive"] },
            mustChangePassword: { type: "boolean" },
          },
        },
        AssignRolesRequest: {
          type: "object",
          required: ["roles"],
          properties: {
            roles: { type: "array", minItems: 1, items: ref("RoleKey") },
          },
        },
        AssignCentersRequest: {
          type: "object",
          required: ["centerIds"],
          properties: {
            centerIds: { type: "array", items: { type: "string" } },
          },
        },
        UserListData: {
          type: "object",
          required: ["items", "total", "page", "pageSize"],
          properties: {
            items: { type: "array", items: ref("User") },
            total: { type: "integer", minimum: 0 },
            page: { type: "integer", minimum: 1 },
            pageSize: { type: "integer", minimum: 1, maximum: 100 },
          },
        },
        TrainingCenter: {
          type: "object",
          required: [
            "id",
            "centerId",
            "centerName",
            "centerCode",
            "sidhTcId",
            "district",
            "state",
            "programIds",
            "status",
            "createdAt",
            "updatedAt",
          ],
          properties: {
            id: { type: "string", example: "tc_0a1b2c3d4e5f6g7h" },
            centerId: { type: "string" },
            centerName: { type: "string", example: "Gram Tarang Skill Training Center Jharsuguda" },
            centerCode: { type: "string", example: "GTET-JSG-001" },
            sidhTcId: { type: "string", nullable: true, example: "TC164648" },
            district: { type: "string", example: "Jharsuguda" },
            state: { type: "string", example: "Odisha" },
            programIds: { type: "array", items: { type: "string" } },
            status: { type: "string", enum: ["active", "inactive"] },
            createdAt: { type: "string", nullable: true, format: "date-time" },
            updatedAt: { type: "string", nullable: true, format: "date-time" },
          },
        },
        CreateTrainingCenterRequest: {
          type: "object",
          required: ["centerName", "centerCode", "district", "state"],
          properties: {
            centerName: { type: "string", minLength: 3, maxLength: 160 },
            centerCode: { type: "string", minLength: 3, maxLength: 60 },
            sidhTcId: { type: "string" },
            district: { type: "string", minLength: 2, maxLength: 120 },
            state: { type: "string", minLength: 2, maxLength: 120 },
            programIds: { type: "array", items: { type: "string" } },
            status: { type: "string", enum: ["active", "inactive"] },
          },
        },
        TrainingCenterListData: {
          type: "object",
          required: ["items", "total", "page", "pageSize"],
          properties: {
            items: { type: "array", items: ref("TrainingCenter") },
            total: { type: "integer", minimum: 0 },
            page: { type: "integer", minimum: 1 },
            pageSize: { type: "integer", minimum: 1, maximum: 100 },
          },
        },
        Program: {
          type: "object",
          required: ["id", "programId", "name", "code", "description", "syncToSidh", "status", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            programId: { type: "string" },
            name: { type: "string" },
            code: { type: "string" },
            description: { type: "string", nullable: true },
            syncToSidh: { type: "boolean" },
            status: { type: "string", enum: ["active", "inactive"] },
            createdAt: { type: "string", nullable: true, format: "date-time" },
            updatedAt: { type: "string", nullable: true, format: "date-time" },
          },
        },
        ProgramListData: {
          type: "object",
          required: ["items", "total", "page", "pageSize"],
          properties: {
            items: { type: "array", items: ref("Program") },
            total: { type: "integer", minimum: 0 },
            page: { type: "integer", minimum: 1 },
            pageSize: { type: "integer", minimum: 1, maximum: 100 },
          },
        },
        CreateProgramRequest: {
          type: "object",
          required: ["name", "code"],
          properties: {
            name: { type: "string" },
            code: { type: "string" },
            description: { type: "string" },
            syncToSidh: { type: "boolean" },
            status: { type: "string", enum: ["active", "inactive"] },
          },
        },
        UpdateProgramRequest: {
          type: "object",
          properties: {
            name: { type: "string" },
            code: { type: "string" },
            description: { type: "string" },
            syncToSidh: { type: "boolean" },
            status: { type: "string", enum: ["active", "inactive"] },
          },
        },
        Sector: {
          type: "object",
          required: ["id", "sectorId", "name", "code", "description", "status", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            sectorId: { type: "string" },
            name: { type: "string" },
            code: { type: "string" },
            description: { type: "string", nullable: true },
            status: { type: "string", enum: ["active", "inactive"] },
            createdAt: { type: "string", nullable: true, format: "date-time" },
            updatedAt: { type: "string", nullable: true, format: "date-time" },
          },
        },
        SectorListData: {
          type: "object",
          required: ["items", "total", "page", "pageSize"],
          properties: {
            items: { type: "array", items: ref("Sector") },
            total: { type: "integer", minimum: 0 },
            page: { type: "integer", minimum: 1 },
            pageSize: { type: "integer", minimum: 1, maximum: 100 },
          },
        },
        CreateSectorRequest: {
          type: "object",
          required: ["name", "code"],
          properties: {
            name: { type: "string" },
            code: { type: "string" },
            description: { type: "string" },
            status: { type: "string", enum: ["active", "inactive"] },
          },
        },
        Scheme: {
          type: "object",
          required: ["id", "schemeId", "name", "code", "description", "status", "syncEnabled", "sidhSchemeId", "fundingType", "beneficiaryType", "validFrom", "validTo", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            schemeId: { type: "string" },
            name: { type: "string" },
            code: { type: "string" },
            description: { type: "string", nullable: true },
            status: { type: "string", enum: ["active", "inactive"] },
            syncEnabled: { type: "boolean" },
            sidhSchemeId: { type: "string", nullable: true },
            fundingType: { type: "string", nullable: true },
            beneficiaryType: { type: "string", nullable: true },
            validFrom: { type: "string", nullable: true, format: "date-time" },
            validTo: { type: "string", nullable: true, format: "date-time" },
            createdAt: { type: "string", nullable: true, format: "date-time" },
            updatedAt: { type: "string", nullable: true, format: "date-time" },
          },
        },
        SchemeListData: {
          type: "object",
          required: ["items", "total", "page", "pageSize"],
          properties: {
            items: { type: "array", items: ref("Scheme") },
            total: { type: "integer", minimum: 0 },
            page: { type: "integer", minimum: 1 },
            pageSize: { type: "integer", minimum: 1, maximum: 100 },
          },
        },
        CreateSchemeRequest: {
          type: "object",
          required: ["name", "code"],
          properties: {
            name: { type: "string" },
            code: { type: "string" },
            description: { type: "string" },
            status: { type: "string", enum: ["active", "inactive"] },
            syncEnabled: { type: "boolean" },
            sidhSchemeId: { type: "string" },
            fundingType: { type: "string" },
            beneficiaryType: { type: "string" },
            validFrom: { type: "string", format: "date" },
            validTo: { type: "string", format: "date" },
          },
        },
        UpdateSchemeRequest: {
          type: "object",
          properties: {
            name: { type: "string" },
            code: { type: "string" },
            description: { type: "string" },
            status: { type: "string", enum: ["active", "inactive"] },
            syncEnabled: { type: "boolean" },
            sidhSchemeId: { type: "string" },
            fundingType: { type: "string" },
            beneficiaryType: { type: "string" },
            validFrom: { type: "string", format: "date" },
            validTo: { type: "string", format: "date" },
          },
        },
        Course: {
          type: "object",
          required: ["id", "courseId", "sectorId", "programIds", "schemeIds", "courseName", "internalCourseCode", "sidhCourseId", "associatedQpOrJobRole", "nsqfLevel", "trainingHours", "gtUploadedDurationHours", "approvalStatus", "approvalDate", "validityStartDate", "validityEndDate", "minimumAge", "price", "qpCode", "jobRoleMappingType", "status", "version", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            courseId: { type: "string" },
            sectorId: { type: "string" },
            programIds: { type: "array", items: { type: "string" } },
            schemeIds: { type: "array", items: { type: "string" } },
            courseName: { type: "string" },
            internalCourseCode: { type: "string" },
            sidhCourseId: { type: "string" },
            associatedQpOrJobRole: { type: "string" },
            nsqfLevel: { type: "number" },
            trainingHours: { type: "number" },
            gtUploadedDurationHours: { type: "number", nullable: true },
            approvalStatus: { type: "string", enum: ["approved", "pending", "rejected", "expired"] },
            approvalDate: { type: "string", nullable: true, format: "date-time" },
            validityStartDate: { type: "string", format: "date-time" },
            validityEndDate: { type: "string", format: "date-time" },
            minimumAge: { type: "number" },
            price: { type: "number" },
            qpCode: { type: "string" },
            jobRoleMappingType: { type: "string", enum: ["QP_NOS", "JOB_ROLE", "HYBRID"] },
            status: { type: "string", enum: ["active", "inactive"] },
            version: { type: "integer", minimum: 1 },
            createdAt: { type: "string", nullable: true, format: "date-time" },
            updatedAt: { type: "string", nullable: true, format: "date-time" },
          },
        },
        CourseListData: {
          type: "object",
          required: ["items", "total", "page", "pageSize"],
          properties: {
            items: { type: "array", items: ref("Course") },
            total: { type: "integer", minimum: 0 },
            page: { type: "integer", minimum: 1 },
            pageSize: { type: "integer", minimum: 1, maximum: 100 },
          },
        },
        CreateCourseRequest: {
          type: "object",
          required: ["sectorId", "courseName", "internalCourseCode", "sidhCourseId", "associatedQpOrJobRole", "nsqfLevel", "trainingHours", "validityStartDate", "validityEndDate", "minimumAge", "price", "qpCode", "jobRoleMappingType"],
          properties: {
            sectorId: { type: "string" },
            programIds: { type: "array", items: { type: "string" } },
            schemeIds: { type: "array", items: { type: "string" } },
            courseName: { type: "string" },
            internalCourseCode: { type: "string" },
            sidhCourseId: { type: "string" },
            associatedQpOrJobRole: { type: "string" },
            nsqfLevel: { type: "number" },
            trainingHours: { type: "number" },
            gtUploadedDurationHours: { type: "number" },
            approvalStatus: { type: "string", enum: ["approved", "pending", "rejected", "expired"] },
            approvalDate: { type: "string", format: "date" },
            validityStartDate: { type: "string", format: "date" },
            validityEndDate: { type: "string", format: "date" },
            minimumAge: { type: "number" },
            price: { type: "number" },
            qpCode: { type: "string" },
            jobRoleMappingType: { type: "string", enum: ["QP_NOS", "JOB_ROLE", "HYBRID"] },
            status: { type: "string", enum: ["active", "inactive"] },
          },
        },
        UpdateCourseRequest: {
          type: "object",
          properties: {
            sectorId: { type: "string" },
            programIds: { type: "array", items: { type: "string" } },
            schemeIds: { type: "array", items: { type: "string" } },
            courseName: { type: "string" },
            internalCourseCode: { type: "string" },
            sidhCourseId: { type: "string" },
            associatedQpOrJobRole: { type: "string" },
            nsqfLevel: { type: "number" },
            trainingHours: { type: "number" },
            gtUploadedDurationHours: { type: "number" },
            approvalStatus: { type: "string", enum: ["approved", "pending", "rejected", "expired"] },
            approvalDate: { type: "string", format: "date" },
            validityStartDate: { type: "string", format: "date" },
            validityEndDate: { type: "string", format: "date" },
            minimumAge: { type: "number" },
            price: { type: "number" },
            qpCode: { type: "string" },
            jobRoleMappingType: { type: "string", enum: ["QP_NOS", "JOB_ROLE", "HYBRID"] },
            status: { type: "string", enum: ["active", "inactive"] },
            currentVersion: { type: "integer", minimum: 1 },
          },
        },
        CourseVersion: {
          type: "object",
          required: ["courseId", "version", "changedByUserId", "changeSummary", "createdAt", "snapshot"],
          properties: {
            courseId: { type: "string" },
            version: { type: "integer", minimum: 1 },
            changedByUserId: { type: "string", nullable: true },
            changeSummary: { type: "string", nullable: true },
            createdAt: { type: "string", nullable: true, format: "date-time" },
            snapshot: { type: "object", additionalProperties: true },
          },
        },
        CandidateReferenceData: {
          type: "object",
          required: ["programs", "sectors", "schemes", "trainingCenters", "courses", "enums"],
          properties: {
            programs: { type: "array", items: ref("Program") },
            sectors: { type: "array", items: ref("Sector") },
            schemes: { type: "array", items: ref("Scheme") },
            trainingCenters: {
              type: "array",
              items: {
                type: "object",
                required: ["id", "centerId", "centerName", "centerCode"],
                properties: {
                  id: { type: "string" },
                  centerId: { type: "string" },
                  centerName: { type: "string" },
                  centerCode: { type: "string" },
                },
              },
            },
            courses: { type: "array", items: ref("Course") },
            enums: {
              type: "object",
              additionalProperties: {
                type: "array",
                items: {
                  type: "object",
                  required: ["code", "label"],
                  properties: {
                    code: { type: "string" },
                    label: { type: "string" },
                  },
                },
              },
            },
          },
        },
        CandidateRegistrationMode: {
          type: "string",
          enum: ["internal_registration", "existing_sidh_link"],
        },
        CandidateSyncStatus: {
          type: "string",
          enum: ["not_queued", "queued", "processing", "synced", "failed", "manual_review", "linked"],
        },
        SyncJobStatus: {
          type: "string",
          enum: ["queued", "processing", "succeeded", "failed", "manual_review", "dead_letter"],
        },
        CandidateAddress: {
          type: "object",
          required: ["address", "state", "district", "pinCode", "city", "tehsil", "constituency"],
          properties: {
            address: { type: "string", nullable: true },
            state: { type: "string", nullable: true },
            district: { type: "string", nullable: true },
            pinCode: { type: "string", nullable: true },
            city: { type: "string", nullable: true },
            tehsil: { type: "string", nullable: true },
            constituency: { type: "string", nullable: true },
          },
        },
        CandidateCommunicationAddress: {
          allOf: [
            ref("CandidateAddress"),
            {
              type: "object",
              required: ["sameAsPermanent"],
              properties: {
                sameAsPermanent: { type: "boolean" },
              },
            },
          ],
        },
        CandidatePersonalDetails: {
          type: "object",
          required: ["fullName", "gender", "dateOfBirth", "disability"],
          properties: {
            salutation: { type: "string", nullable: true },
            fullName: { type: "string" },
            gender: { type: "string", nullable: true },
            dateOfBirth: { type: "string", format: "date", nullable: true },
            maritalStatus: { type: "string", nullable: true },
            fathersName: { type: "string", nullable: true },
            mothersName: { type: "string", nullable: true },
            guardiansName: { type: "string", nullable: true },
            religion: { type: "string", nullable: true },
            category: { type: "string", nullable: true },
            disability: { type: "boolean" },
            typeOfDisability: { type: "string", nullable: true },
            educationLevel: { type: "string", nullable: true },
          },
        },
        CandidateContactDetails: {
          type: "object",
          required: ["mobileNumber"],
          properties: {
            email: { type: "string", format: "email", nullable: true },
            countryCode: { type: "string", nullable: true },
            mobileNumber: { type: "string" },
          },
        },
        CandidateIdentity: {
          type: "object",
          required: ["idType"],
          properties: {
            idType: { type: "string" },
            typeOfAlternateId: { type: "string", nullable: true },
            aadhaarReferenceNo: { type: "string", nullable: true },
            idNumber: { type: "string", nullable: true },
          },
        },
        CandidateDomicile: {
          type: "object",
          required: ["state", "district"],
          properties: {
            state: { type: "string", nullable: true },
            district: { type: "string", nullable: true },
          },
        },
        CandidateExperience: {
          type: "object",
          required: ["trainingStatus"],
          properties: {
            trainingStatus: { type: "string", nullable: true },
            previousExperienceSector: { type: "string", nullable: true },
            monthsOfPreviousExperience: { type: "integer", nullable: true },
            employed: { type: "string", nullable: true },
            employmentStatus: { type: "string", nullable: true },
            employmentDetails: { type: "string", nullable: true },
            heardAboutUs: { type: "string", nullable: true },
          },
        },
        CandidateSyncState: {
          type: "object",
          nullable: true,
          properties: {
            status: ref("CandidateSyncStatus"),
            lastJobId: { type: "string", nullable: true },
            lastAttemptAt: { type: "string", nullable: true, format: "date-time" },
            lastSuccessAt: { type: "string", nullable: true, format: "date-time" },
            lastFailureCode: { type: "string", nullable: true },
            lastFailureMessage: { type: "string", nullable: true },
            retryCount: { type: "integer", minimum: 0 },
          },
        },
        Candidate: {
          type: "object",
          required: [
            "id",
            "candidateId",
            "programId",
            "centerId",
            "registrationMode",
            "personalDetails",
            "contactDetails",
            "domicile",
            "identity",
            "permanentAddress",
            "communicationAddress",
            "experience",
            "sidhCandidateId",
            "syncState",
            "createdAt",
            "updatedAt"
          ],
          properties: {
            id: { type: "string" },
            candidateId: { type: "string" },
            programId: { type: "string" },
            centerId: { type: "string" },
            registrationMode: ref("CandidateRegistrationMode"),
            personalDetails: ref("CandidatePersonalDetails"),
            contactDetails: ref("CandidateContactDetails"),
            domicile: ref("CandidateDomicile"),
            identity: ref("CandidateIdentity"),
            permanentAddress: ref("CandidateAddress"),
            communicationAddress: ref("CandidateCommunicationAddress"),
            experience: ref("CandidateExperience"),
            sidhCandidateId: { type: "string", nullable: true },
            syncState: ref("CandidateSyncState"),
            duplicateHash: { type: "string" },
            createdAt: { type: "string", nullable: true, format: "date-time" },
            updatedAt: { type: "string", nullable: true, format: "date-time" },
          },
        },
        CreateCandidateRequest: {
          type: "object",
          required: [
            "programId",
            "centerId",
            "registrationMode",
            "personalDetails",
            "contactDetails",
            "identity",
            "domicile",
            "permanentAddress",
            "communicationAddress",
            "experience"
          ],
          properties: {
            programId: { type: "string" },
            centerId: { type: "string" },
            registrationMode: ref("CandidateRegistrationMode"),
            personalDetails: ref("CandidatePersonalDetails"),
            contactDetails: ref("CandidateContactDetails"),
            identity: ref("CandidateIdentity"),
            domicile: ref("CandidateDomicile"),
            permanentAddress: ref("CandidateAddress"),
            communicationAddress: ref("CandidateCommunicationAddress"),
            experience: ref("CandidateExperience"),
          },
        },
        UpdateCandidateRequest: {
          type: "object",
          properties: {
            programId: { type: "string" },
            centerId: { type: "string" },
            registrationMode: ref("CandidateRegistrationMode"),
            personalDetails: ref("CandidatePersonalDetails"),
            contactDetails: ref("CandidateContactDetails"),
            identity: ref("CandidateIdentity"),
            domicile: ref("CandidateDomicile"),
            permanentAddress: ref("CandidateAddress"),
            communicationAddress: ref("CandidateCommunicationAddress"),
            experience: ref("CandidateExperience"),
          },
        },
        CandidateListData: {
          type: "object",
          required: ["items", "page", "pageSize", "total"],
          properties: {
            items: { type: "array", items: ref("Candidate") },
            page: { type: "integer", minimum: 1 },
            pageSize: { type: "integer", minimum: 1 },
            total: { type: "integer", minimum: 0 },
          },
        },
        LinkExistingSidhCandidateRequest: {
          type: "object",
          required: ["programId", "centerId", "sidhCandidateId", "mobileNumber", "fullName", "dateOfBirth"],
          properties: {
            programId: { type: "string" },
            centerId: { type: "string" },
            sidhCandidateId: { type: "string" },
            mobileNumber: { type: "string" },
            fullName: { type: "string" },
            dateOfBirth: { type: "string", format: "date" },
          },
        },
        CandidateImportRequest: {
          type: "object",
          required: ["programId", "centerId", "file"],
          properties: {
            programId: { type: "string" },
            centerId: { type: "string" },
            registrationMode: ref("CandidateRegistrationMode"),
            file: { type: "string", format: "binary" },
          },
        },
        CandidateImportJob: {
          type: "object",
          required: [
            "id",
            "importJobId",
            "fileName",
            "status",
            "programId",
            "centerId",
            "registrationMode",
            "totalRows",
            "validRows",
            "invalidRows",
            "duplicateRows",
            "committedRows",
            "committedAt",
            "createdAt",
            "updatedAt"
          ],
          properties: {
            id: { type: "string" },
            importJobId: { type: "string" },
            fileName: { type: "string" },
            status: { type: "string", enum: ["staged", "committed", "failed"] },
            programId: { type: "string" },
            centerId: { type: "string" },
            registrationMode: ref("CandidateRegistrationMode"),
            totalRows: { type: "integer", minimum: 0 },
            validRows: { type: "integer", minimum: 0 },
            invalidRows: { type: "integer", minimum: 0 },
            duplicateRows: { type: "integer", minimum: 0 },
            committedRows: { type: "integer", minimum: 0 },
            committedAt: { type: "string", nullable: true, format: "date-time" },
            createdAt: { type: "string", nullable: true, format: "date-time" },
            updatedAt: { type: "string", nullable: true, format: "date-time" },
          },
        },
        CandidateImportRow: {
          type: "object",
          required: ["rowId", "rowNumber", "status", "errors", "duplicateOfCandidateId", "candidateId", "normalized"],
          properties: {
            rowId: { type: "string" },
            rowNumber: { type: "integer", minimum: 1 },
            status: { type: "string", enum: ["valid", "invalid", "duplicate", "committed", "skipped"] },
            errors: { type: "array", items: ref("ApiErrorDetail") },
            duplicateOfCandidateId: { type: "string", nullable: true },
            candidateId: { type: "string", nullable: true },
            normalized: { type: "object", additionalProperties: true },
          },
        },
        CandidateImportRowListData: {
          type: "object",
          required: ["items", "page", "pageSize", "total"],
          properties: {
            items: { type: "array", items: ref("CandidateImportRow") },
            page: { type: "integer", minimum: 1 },
            pageSize: { type: "integer", minimum: 1 },
            total: { type: "integer", minimum: 0 },
          },
        },
        SyncJob: {
          type: "object",
          required: ["id", "syncJobId", "entityType", "entityId", "candidateId", "status", "retryCount", "latestRemoteCandidateId", "payloadSnapshot", "attempts", "nextRunAt", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            syncJobId: { type: "string" },
            entityType: { type: "string", enum: ["candidate"] },
            entityId: { type: "string" },
            candidateId: { type: "string" },
            status: ref("SyncJobStatus"),
            retryCount: { type: "integer", minimum: 0 },
            latestRemoteCandidateId: { type: "string", nullable: true },
            payloadSnapshot: { type: "object", additionalProperties: true },
            attempts: { type: "array", items: { type: "object", additionalProperties: true } },
            nextRunAt: { type: "string", nullable: true, format: "date-time" },
            createdAt: { type: "string", nullable: true, format: "date-time" },
            updatedAt: { type: "string", nullable: true, format: "date-time" },
          },
        },
        SyncJobTransaction: {
          type: "object",
          required: ["transactionId", "operation", "endpoint", "responseStatus", "success", "createdAt"],
          properties: {
            transactionId: { type: "string" },
            operation: { type: "string" },
            endpoint: { type: "string" },
            responseStatus: { type: "integer", nullable: true },
            success: { type: "boolean" },
            createdAt: { type: "string", nullable: true, format: "date-time" },
          },
        },
        SyncJobDetail: {
          allOf: [
            ref("SyncJob"),
            {
              type: "object",
              required: ["transactions"],
              properties: {
                transactions: { type: "array", items: ref("SyncJobTransaction") },
              },
            },
          ],
        },
        ProcessedSyncJob: {
          type: "object",
          required: ["syncJobId", "candidateId", "status", "message", "remoteCandidateId"],
          properties: {
            syncJobId: { type: "string" },
            candidateId: { type: "string" },
            status: { type: "string", enum: ["queued", "succeeded", "manual_review", "dead_letter"] },
            message: { type: "string" },
            remoteCandidateId: { type: "string", nullable: true },
          },
        },
        ProcessSyncJobsRequest: {
          type: "object",
          properties: {
            limit: { type: "integer", minimum: 1, maximum: 25, default: 5 },
          },
        },
        ProcessSyncJobsResult: {
          type: "object",
          required: ["processedCount", "succeededCount", "retryScheduledCount", "manualReviewCount", "deadLetterCount", "jobs"],
          properties: {
            processedCount: { type: "integer", minimum: 0 },
            succeededCount: { type: "integer", minimum: 0 },
            retryScheduledCount: { type: "integer", minimum: 0 },
            manualReviewCount: { type: "integer", minimum: 0 },
            deadLetterCount: { type: "integer", minimum: 0 },
            jobs: { type: "array", items: ref("ProcessedSyncJob") },
          },
        },
        BatchCandidate: {
          type: "object",
          required: ["batchCandidateId", "candidateId", "candidateName", "candidateMobileNumber", "enrollmentStatus", "sidhCandidateId", "trainingStatus"],
          properties: {
            batchCandidateId: { type: "string" },
            candidateId: { type: "string" },
            candidateName: { type: "string", nullable: true },
            candidateMobileNumber: { type: "string", nullable: true },
            enrollmentStatus: { type: "string", enum: ["not_enrolled", "queued", "processing", "synced", "failed", "manual_review", "cancelled"] },
            sidhCandidateId: { type: "string", nullable: true },
            trainingStatus: { type: "string", nullable: true },
          },
        },
        BatchSyncStateView: {
          type: "object",
          required: ["status", "retryCount", "lastJobId", "lastFailureCode", "lastFailureMessage", "lastSuccessAt", "lastAttemptAt", "remoteStatus", "requestFingerprint", "attempts"],
          properties: {
            status: { type: "string", enum: ["not_synced", "queued", "processing", "synced", "failed", "manual_review", "cancelled"] },
            retryCount: { type: "integer", minimum: 0 },
            lastJobId: { type: "string", nullable: true },
            lastFailureCode: { type: "string", nullable: true },
            lastFailureMessage: { type: "string", nullable: true },
            lastSuccessAt: { type: "string", nullable: true, format: "date-time" },
            lastAttemptAt: { type: "string", nullable: true, format: "date-time" },
            remoteStatus: { type: "string", nullable: true },
            requestFingerprint: { type: "string", nullable: true },
            attempts: { type: "array", items: { type: "object", additionalProperties: true } },
          },
        },
        Batch: {
          type: "object",
          required: ["id", "batchId", "batchCode", "batchName", "batchSize", "courseId", "schemeId", "centerId", "startDate", "endDate", "assessmentDate", "startTime", "endTime", "trainingHoursPerDay", "fee", "status", "syncEnabled", "allowAssessmentBeforeBatchEnd", "allowCandidateOverlap", "assessmentEligibilityThreshold", "candidateCount", "sidhBatchId", "syncState"],
          properties: {
            id: { type: "string" },
            batchId: { type: "string" },
            batchCode: { type: "string" },
            batchName: { type: "string", nullable: true },
            batchSize: { type: "integer", minimum: 1, maximum: 80 },
            courseId: { type: "string" },
            schemeId: { type: "string" },
            centerId: { type: "string" },
            startDate: { type: "string", nullable: true, format: "date" },
            endDate: { type: "string", nullable: true, format: "date" },
            assessmentDate: { type: "string", nullable: true, format: "date" },
            startTime: { type: "string", pattern: "^([01]\\d|2[0-3]):[0-5]\\d$" },
            endTime: { type: "string", pattern: "^([01]\\d|2[0-3]):[0-5]\\d$" },
            trainingHoursPerDay: { type: "integer", minimum: 1, maximum: 24 },
            fee: { type: "number", minimum: 0 },
            status: { type: "string", enum: ["draft", "ready", "active", "completed", "cancelled"] },
            syncEnabled: { type: "boolean" },
            allowAssessmentBeforeBatchEnd: { type: "boolean" },
            allowCandidateOverlap: { type: "boolean" },
            assessmentEligibilityThreshold: { type: "integer", minimum: 0, maximum: 100 },
            candidateCount: { type: "integer", minimum: 0, maximum: 80 },
            sidhBatchId: { type: "string", nullable: true },
            syncState: {
              type: "object",
              required: ["batchSync", "enrollmentSync"],
              properties: {
                batchSync: ref("BatchSyncStateView"),
                enrollmentSync: ref("BatchSyncStateView"),
              },
            },
            candidates: { type: "array", items: ref("BatchCandidate") },
          },
        },
        BatchListData: {
          type: "object",
          required: ["items", "page", "pageSize", "total"],
          properties: {
            items: { type: "array", items: ref("Batch") },
            page: { type: "integer", minimum: 1 },
            pageSize: { type: "integer", minimum: 1 },
            total: { type: "integer", minimum: 0 },
          },
        },
        CreateBatchRequest: {
          type: "object",
          required: ["batchCode", "courseId", "schemeId", "centerId", "startDate", "endDate", "assessmentDate"],
          properties: {
            batchCode: { type: "string" },
            batchName: { type: "string" },
            batchSize: { type: "integer", minimum: 1, maximum: 80, default: 80 },
            courseId: { type: "string" },
            schemeId: { type: "string" },
            centerId: { type: "string" },
            startDate: { type: "string", format: "date" },
            endDate: { type: "string", format: "date" },
            assessmentDate: { type: "string", format: "date" },
            startTime: { type: "string", pattern: "^([01]\\d|2[0-3]):[0-5]\\d$", default: "09:00" },
            endTime: { type: "string", pattern: "^([01]\\d|2[0-3]):[0-5]\\d$", default: "17:00" },
            trainingHoursPerDay: { type: "integer", minimum: 1, maximum: 24, default: 8 },
            fee: { type: "number", minimum: 0, default: 0 },
            assessmentEligibilityThreshold: { type: "integer", minimum: 0, maximum: 100, default: 70 },
            candidateIds: { type: "array", items: { type: "string" }, maxItems: 80 },
            syncEnabled: { type: "boolean", default: true },
            status: { type: "string", enum: ["draft", "ready", "active", "completed", "cancelled"] },
          },
        },
        UpdateBatchRequest: {
          type: "object",
          properties: {
            batchCode: { type: "string" },
            batchName: { type: "string" },
            batchSize: { type: "integer", minimum: 1, maximum: 80 },
            courseId: { type: "string" },
            schemeId: { type: "string" },
            centerId: { type: "string" },
            startDate: { type: "string", format: "date" },
            endDate: { type: "string", format: "date" },
            assessmentDate: { type: "string", format: "date" },
            startTime: { type: "string", pattern: "^([01]\\d|2[0-3]):[0-5]\\d$" },
            endTime: { type: "string", pattern: "^([01]\\d|2[0-3]):[0-5]\\d$" },
            trainingHoursPerDay: { type: "integer", minimum: 1, maximum: 24 },
            fee: { type: "number", minimum: 0 },
            assessmentEligibilityThreshold: { type: "integer", minimum: 0, maximum: 100 },
            syncEnabled: { type: "boolean" },
            status: { type: "string", enum: ["draft", "ready", "active", "completed", "cancelled"] },
          },
        },
        AddCandidatesToBatchRequest: {
          type: "object",
          required: ["candidateIds"],
          properties: {
            candidateIds: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 80 },
          },
        },
        BatchSyncRequest: {
          type: "object",
          properties: {
            forceResync: { type: "boolean", default: false },
          },
        },
        EnrollmentSyncRequest: {
          type: "object",
          properties: {
            candidateIds: { type: "array", items: { type: "string" } },
            forceResync: { type: "boolean", default: false },
          },
        },
        TrainingAssessmentTrainingDetails: {
          type: "object",
          required: ["trainingStatus", "attendance"],
          properties: {
            trainingStatus: { type: "string", example: "completed" },
            attendance: { type: "integer", minimum: 0, maximum: 100 },
          },
        },
        TrainingAssessmentAssessmentDetails: {
          type: "object",
          required: ["assessmentStatus", "assessmentPercentage", "assessmentDataUploadedOn", "assessmentAgency", "assessorID", "assessorName"],
          properties: {
            assessmentStatus: { type: "string", example: "Pass" },
            assessmentPercentage: { type: "integer", minimum: 0, maximum: 100 },
            grade: { type: "string" },
            assessmentDataUploadedOn: { type: "string", example: "2026-02-05" },
            assessmentAgency: { type: "string", default: "Self" },
            assessorID: { type: "string" },
            assessorName: { type: "string" },
          },
        },
        TrainingAssessmentCertificationDetails: {
          type: "object",
          required: ["certificationName", "isCertified", "certifyingAgency", "certificationDate"],
          properties: {
            certificationName: { type: "string" },
            isCertified: { type: "boolean" },
            certifyingAgency: { type: "string" },
            certificationDate: { type: "string", example: "2026-02-05" },
          },
        },
        TrainingAssessmentCandidate: {
          type: "object",
          required: ["candidateID", "trainingDetails", "assessmentDetails", "certificationDetails"],
          properties: {
            candidateID: { type: "string" },
            trainingDetails: ref("TrainingAssessmentTrainingDetails"),
            assessmentDetails: ref("TrainingAssessmentAssessmentDetails"),
            certificationDetails: ref("TrainingAssessmentCertificationDetails"),
          },
        },
        TrainingAssessmentSubmissionRequest: {
          type: "object",
          required: ["candidates"],
          properties: {
            batchId: { oneOf: [{ type: "string" }, { type: "integer" }] },
            candidates: { type: "array", minItems: 1, items: ref("TrainingAssessmentCandidate") },
          },
        },
        CertificateGenerationRequest: {
          type: "object",
          oneOf: [{ required: ["candidateId"] }, { required: ["userName"] }],
          properties: {
            candidateId: { type: "string", description: "SIDH candidate ID. Sent as userName to SIDH when userName is omitted." },
            userName: { type: "string", description: "SIDH userName/candidate ID expected by the certificate API." },
          },
        },
        SidhOperationResult: {
          type: "object",
          required: ["responseBody", "responseStatus"],
          properties: {
            responseBody: { nullable: true, additionalProperties: true },
            responseStatus: { type: "integer" },
          },
        },
        BatchStatus: {
          type: "object",
          required: ["batchId", "batchCode", "candidateCount", "sidhBatchId", "batchSync", "enrollmentSync", "enrollmentCounts"],
          properties: {
            batchId: { type: "string" },
            batchCode: { type: "string" },
            candidateCount: { type: "integer", minimum: 0, maximum: 80 },
            sidhBatchId: { type: "string", nullable: true },
            batchSync: ref("BatchSyncStateView"),
            enrollmentSync: ref("BatchSyncStateView"),
            enrollmentCounts: { type: "object", additionalProperties: { type: "integer", minimum: 0 } },
          },
        },
        AttendanceImportRequest: {
          type: "object",
          required: ["batchId", "file"],
          properties: {
            batchId: { type: "string" },
            file: { type: "string", format: "binary" },
          },
        },
        AttendanceImportRow: {
          type: "object",
          required: ["rowId", "rowNumber", "candidateId", "attendanceDate", "attendanceStatus", "trainingStatus", "status", "errors", "normalized"],
          properties: {
            rowId: { type: "string" },
            rowNumber: { type: "integer", minimum: 1 },
            candidateId: { type: "string", nullable: true },
            attendanceDate: { type: "string", nullable: true, format: "date" },
            attendanceStatus: { type: "string", nullable: true, enum: ["present", "absent"] },
            trainingStatus: { type: "string", nullable: true, enum: ["ongoing", "completed", "dropout"] },
            status: { type: "string", enum: ["valid", "invalid", "duplicate"] },
            errors: { type: "array", items: ref("ApiErrorDetail") },
            normalized: { type: "object", additionalProperties: true },
          },
        },
        AttendanceImportJob: {
          type: "object",
          required: ["id", "attendanceUploadId", "batchId", "fileName", "status", "totalRows", "validRows", "invalidRows", "committedRows", "committedAt", "createdAt", "updatedAt", "rows"],
          properties: {
            id: { type: "string" },
            attendanceUploadId: { type: "string" },
            batchId: { type: "string" },
            fileName: { type: "string" },
            status: { type: "string", enum: ["staged", "validated", "committed", "failed"] },
            totalRows: { type: "integer", minimum: 0 },
            validRows: { type: "integer", minimum: 0 },
            invalidRows: { type: "integer", minimum: 0 },
            committedRows: { type: "integer", minimum: 0 },
            committedAt: { type: "string", nullable: true, format: "date-time" },
            createdAt: { type: "string", nullable: true, format: "date-time" },
            updatedAt: { type: "string", nullable: true, format: "date-time" },
            rows: { type: "array", items: ref("AttendanceImportRow") },
          },
        },
        AttendanceCommitRequest: {
          type: "object",
          properties: {
            overwriteExisting: { type: "boolean", default: false },
          },
        },
        AttendanceDaySummary: {
          type: "object",
          required: ["attendanceDate", "presentCount", "absentCount", "expectedCandidateCount"],
          properties: {
            attendanceDate: { type: "string", nullable: true, format: "date" },
            presentCount: { type: "integer", minimum: 0 },
            absentCount: { type: "integer", minimum: 0 },
            expectedCandidateCount: { type: "integer", minimum: 0 },
          },
        },
        AttendanceCandidateSummary: {
          type: "object",
          required: ["candidateId", "candidateName", "attendancePercentage", "presentDays", "totalSessions", "trainingStatus", "eligibleForAssessment", "enrollmentStatus"],
          properties: {
            candidateId: { type: "string" },
            candidateName: { type: "string", nullable: true },
            attendancePercentage: { type: "number", format: "double" },
            presentDays: { type: "integer", minimum: 0 },
            totalSessions: { type: "integer", minimum: 0 },
            trainingStatus: { type: "string", nullable: true },
            eligibleForAssessment: { type: "boolean" },
            enrollmentStatus: { type: "string" },
          },
        },
        AttendanceSummary: {
          type: "object",
          required: ["batchId", "assessmentEligibilityThreshold", "totalSessions", "dailySessions", "candidates"],
          properties: {
            batchId: { type: "string" },
            assessmentEligibilityThreshold: { type: "integer", minimum: 0, maximum: 100 },
            totalSessions: { type: "integer", minimum: 0 },
            dailySessions: { type: "array", items: ref("AttendanceDaySummary") },
            candidates: { type: "array", items: ref("AttendanceCandidateSummary") },
          },
        },
        SyncJobListData: {
          type: "object",
          required: ["items", "page", "pageSize", "total"],
          properties: {
            items: { type: "array", items: ref("SyncJob") },
            page: { type: "integer", minimum: 1 },
            pageSize: { type: "integer", minimum: 1 },
            total: { type: "integer", minimum: 0 },
          },
        },
        HealthData: {
          type: "object",
          required: ["status", "appEnv", "nodeEnv", "sidhEnv", "sidhBaseUrl", "timestamp"],
          properties: {
            status: { type: "string", example: "ok" },
            appEnv: { type: "string" },
            nodeEnv: { type: "string" },
            sidhEnv: { type: "string", enum: ["uat", "production"] },
            sidhBaseUrl: { type: "string", format: "uri" },
            timestamp: { type: "string", format: "date-time" },
          },
        },
        ReadinessData: {
          type: "object",
          required: ["status", "databaseState"],
          properties: {
            status: { type: "string", example: "ready" },
            databaseState: { type: "integer", example: 1 },
          },
        },
        OpenApiDocument: {
          type: "object",
          description: "Self-describing OpenAPI document returned by this endpoint",
          additionalProperties: true,
        },
      },
    },
    paths: {
      "/auth/login": {
        post: {
          tags: ["Auth"],
          summary: "Authenticate a portal user and issue a session cookie",
          requestBody: {
            required: true,
            content: jsonContent(ref("LoginRequest")),
          },
          responses: {
            200: successResponse("Login successful", ref("LoginResponseData")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Invalid credentials"),
            403: errorResponse("Portal access denied or user inactive"),
            500: errorResponse("Unexpected server error"),
          },
        },
      },
      "/auth/forgot-password/request": {
        post: {
          tags: ["Auth"],
          summary: "Send a password reset OTP",
          requestBody: {
            required: true,
            content: jsonContent(ref("ForgotPasswordRequest")),
          },
          responses: {
            200: successResponse("OTP request accepted", ref("MessageData")),
            400: errorResponse("Validation failed"),
            500: errorResponse("SMTP not configured or email delivery failed"),
          },
        },
      },
      "/auth/forgot-password/reset": {
        post: {
          tags: ["Auth"],
          summary: "Reset a password using email, portal, and OTP",
          requestBody: {
            required: true,
            content: jsonContent(ref("ForgotPasswordResetRequest")),
          },
          responses: {
            200: successResponse("Password reset completed", ref("PasswordResetResponseData")),
            400: errorResponse("Validation failed or OTP is invalid/expired"),
            500: errorResponse("Unexpected server error"),
          },
        },
      },
      "/auth/logout": {
        post: {
          tags: ["Auth"],
          summary: "Logout the current user",
          security: [{ cookieAuth: [] }],
          responses: {
            200: successResponse("Logout successful", { type: "object", additionalProperties: false }),
            401: errorResponse("Authentication required"),
          },
        },
      },
      "/auth/me": {
        get: {
          tags: ["Auth"],
          summary: "Get the current authenticated user",
          security: [{ cookieAuth: [] }],
          responses: {
            200: successResponse("Authenticated user loaded", ref("AuthMeData")),
            401: errorResponse("Authentication required"),
          },
        },
      },
      "/admin/users": {
        get: {
          tags: ["Admin Users"],
          summary: "List users in the caller's visible scope",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/Page" }, { $ref: "#/components/parameters/PageSize" }],
          responses: {
            200: successResponse("Users loaded", ref("UserListData")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
        post: {
          tags: ["Admin Users"],
          summary: "Create a new internal user",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: true,
            content: jsonContent(ref("CreateUserRequest")),
          },
          responses: {
            201: successResponse("User created successfully", ref("User")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            409: errorResponse("User already exists or invalid scope assignment"),
          },
        },
      },
      "/admin/users/{userId}": {
        get: {
          tags: ["Admin Users"],
          summary: "Get a specific user",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/UserId" }],
          responses: {
            200: successResponse("User loaded", ref("User")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("User not found"),
          },
        },
        patch: {
          tags: ["Admin Users"],
          summary: "Update a specific user",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/UserId" }],
          requestBody: {
            required: true,
            content: jsonContent(ref("UpdateUserRequest")),
          },
          responses: {
            200: successResponse("User updated successfully", ref("User")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("User not found"),
            409: errorResponse("User already exists"),
          },
        },
      },
      "/admin/users/{userId}/roles": {
        post: {
          tags: ["Admin Users"],
          summary: "Assign roles to a user",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/UserId" }],
          requestBody: {
            required: true,
            content: jsonContent(ref("AssignRolesRequest")),
          },
          responses: {
            200: successResponse("User roles assigned successfully", ref("User")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("User not found"),
          },
        },
      },
      "/admin/users/{userId}/centers": {
        post: {
          tags: ["Admin Users"],
          summary: "Assign training centers to a user",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/UserId" }],
          requestBody: {
            required: true,
            content: jsonContent(ref("AssignCentersRequest")),
          },
          responses: {
            200: successResponse("User centers assigned successfully", ref("User")),
            400: errorResponse("Validation failed or center not found"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("User not found"),
          },
        },
      },
      "/masters/training-centers": {
        get: {
          tags: ["Masters"],
          summary: "List training centers in visible scope",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/Page" }, { $ref: "#/components/parameters/PageSize" }],
          responses: {
            200: successResponse("Training centers loaded", ref("TrainingCenterListData")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
        post: {
          tags: ["Masters"],
          summary: "Create a training center",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: true,
            content: jsonContent(ref("CreateTrainingCenterRequest")),
          },
          responses: {
            201: successResponse("Training center created successfully", ref("TrainingCenter")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            409: errorResponse("Training center already exists"),
          },
        },
      },
      "/masters/training-centers/{centerId}": {
        patch: {
          tags: ["Masters"],
          summary: "Update a training center",
          security: [{ cookieAuth: [] }],
          parameters: [{ name: "centerId", in: "path", required: true, schema: { type: "string" } }],
          requestBody: {
            required: true,
            content: jsonContent(ref("CreateTrainingCenterRequest")),
          },
          responses: {
            200: successResponse("Training center updated successfully", ref("TrainingCenter")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Training center not found"),
            409: errorResponse("Training center conflict"),
          },
        },
      },
      "/masters/programs": {
        get: {
          tags: ["Masters"],
          summary: "List programs",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/Page" }, { $ref: "#/components/parameters/PageSize" }],
          responses: {
            200: successResponse("Programs loaded", ref("ProgramListData")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
        post: {
          tags: ["Masters"],
          summary: "Create a program",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: true,
            content: jsonContent(ref("CreateProgramRequest")),
          },
          responses: {
            201: successResponse("Program created successfully", ref("Program")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            409: errorResponse("Program already exists"),
          },
        },
      },
      "/masters/programs/{programId}": {
        patch: {
          tags: ["Masters"],
          summary: "Update a program",
          security: [{ cookieAuth: [] }],
          parameters: [{ name: "programId", in: "path", required: true, schema: { type: "string" } }],
          requestBody: {
            required: true,
            content: jsonContent(ref("UpdateProgramRequest")),
          },
          responses: {
            200: successResponse("Program updated successfully", ref("Program")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Program not found"),
            409: errorResponse("Program already exists"),
          },
        },
      },
      "/masters/sectors": {
        get: {
          tags: ["Masters"],
          summary: "List sectors",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/Page" }, { $ref: "#/components/parameters/PageSize" }],
          responses: {
            200: successResponse("Sectors loaded", ref("SectorListData")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
        post: {
          tags: ["Masters"],
          summary: "Create a sector",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: true,
            content: jsonContent(ref("CreateSectorRequest")),
          },
          responses: {
            201: successResponse("Sector created successfully", ref("Sector")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            409: errorResponse("Sector already exists"),
          },
        },
      },
      "/masters/schemes": {
        get: {
          tags: ["Masters"],
          summary: "List schemes",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/Page" }, { $ref: "#/components/parameters/PageSize" }],
          responses: {
            200: successResponse("Schemes loaded", ref("SchemeListData")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
        post: {
          tags: ["Masters"],
          summary: "Create a scheme",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: true,
            content: jsonContent(ref("CreateSchemeRequest")),
          },
          responses: {
            201: successResponse("Scheme created successfully", ref("Scheme")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            409: errorResponse("Scheme already exists"),
          },
        },
      },
      "/masters/schemes/{schemeId}": {
        patch: {
          tags: ["Masters"],
          summary: "Update a scheme",
          security: [{ cookieAuth: [] }],
          parameters: [{ name: "schemeId", in: "path", required: true, schema: { type: "string" } }],
          requestBody: {
            required: true,
            content: jsonContent(ref("UpdateSchemeRequest")),
          },
          responses: {
            200: successResponse("Scheme updated successfully", ref("Scheme")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Scheme not found"),
          },
        },
      },
      "/masters/courses": {
        get: {
          tags: ["Masters"],
          summary: "List courses",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/Page" }, { $ref: "#/components/parameters/PageSize" }],
          responses: {
            200: successResponse("Courses loaded", ref("CourseListData")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
        post: {
          tags: ["Masters"],
          summary: "Create a course mapping",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: true,
            content: jsonContent(ref("CreateCourseRequest")),
          },
          responses: {
            201: successResponse("Course created successfully", ref("Course")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            409: errorResponse("Course mapping conflict"),
          },
        },
      },
      "/masters/courses/{courseId}": {
        patch: {
          tags: ["Masters"],
          summary: "Update a course mapping",
          security: [{ cookieAuth: [] }],
          parameters: [{ name: "courseId", in: "path", required: true, schema: { type: "string" } }],
          requestBody: {
            required: true,
            content: jsonContent(ref("UpdateCourseRequest")),
          },
          responses: {
            200: successResponse("Course updated successfully", ref("Course")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Course not found"),
            409: errorResponse("Course mapping conflict"),
          },
        },
      },
      "/masters/courses/{courseId}/versions": {
        get: {
          tags: ["Masters"],
          summary: "List course mapping versions",
          security: [{ cookieAuth: [] }],
          parameters: [{ name: "courseId", in: "path", required: true, schema: { type: "string" } }],
          responses: {
            200: successResponse("Course versions loaded", { type: "array", items: ref("CourseVersion") }),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
      },
      "/reference-data/candidate": {
        get: {
          tags: ["Reference Data"],
          summary: "Get candidate reference data",
          security: [{ cookieAuth: [] }],
          responses: {
            200: successResponse("Candidate reference data loaded", ref("CandidateReferenceData")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
      },
      "/candidates": {
        get: {
          tags: ["Candidates"],
          summary: "List candidates in the caller's visible scope",
          security: [{ cookieAuth: [] }],
          parameters: [
            { $ref: "#/components/parameters/Page" },
            { $ref: "#/components/parameters/PageSize" },
            { name: "search", in: "query", schema: { type: "string" } },
            { name: "programId", in: "query", schema: { type: "string" } },
            { name: "centerId", in: "query", schema: { type: "string" } },
            { name: "syncStatus", in: "query", schema: ref("CandidateSyncStatus") },
            { name: "registrationMode", in: "query", schema: ref("CandidateRegistrationMode") },
          ],
          responses: {
            200: successResponse("Candidates loaded", ref("CandidateListData")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
        post: {
          tags: ["Candidates"],
          summary: "Create a candidate record without calling SIDH directly",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: true,
            content: jsonContent(ref("CreateCandidateRequest")),
          },
          responses: {
            201: successResponse("Candidate created successfully", ref("Candidate")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            409: errorResponse("Duplicate candidate"),
          },
        },
      },
      "/candidates/{candidateId}": {
        get: {
          tags: ["Candidates"],
          summary: "Get a specific candidate",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/CandidateId" }],
          responses: {
            200: successResponse("Candidate loaded", ref("Candidate")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Candidate not found"),
          },
        },
        patch: {
          tags: ["Candidates"],
          summary: "Update a specific candidate",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/CandidateId" }],
          requestBody: {
            required: true,
            content: jsonContent(ref("UpdateCandidateRequest")),
          },
          responses: {
            200: successResponse("Candidate updated successfully", ref("Candidate")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Candidate not found"),
            409: errorResponse("Duplicate candidate"),
          },
        },
      },
      "/candidates/link-existing-sidh": {
        post: {
          tags: ["Candidates"],
          summary: "Link an already-existing SIDH candidate using SIDH candidate ID and mobile number",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: true,
            content: jsonContent(ref("LinkExistingSidhCandidateRequest")),
          },
          responses: {
            201: successResponse("Existing SIDH candidate linked successfully", ref("Candidate")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            409: errorResponse("SIDH candidate already linked or duplicate found"),
          },
        },
      },
      "/candidates/imports": {
        post: {
          tags: ["Candidates"],
          summary: "Stage a bulk candidate workbook for row-level validation",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: true,
            content: {
              "multipart/form-data": {
                schema: ref("CandidateImportRequest"),
              },
            },
          },
          responses: {
            201: successResponse("Candidate import staged successfully", ref("CandidateImportJob")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
      },
      "/candidates/imports/{jobId}": {
        get: {
          tags: ["Candidates"],
          summary: "Get a staged candidate import job summary",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/ImportJobId" }],
          responses: {
            200: successResponse("Candidate import job loaded", ref("CandidateImportJob")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Import job not found"),
          },
        },
      },
      "/candidates/imports/{jobId}/rows": {
        get: {
          tags: ["Candidates"],
          summary: "List row-level validation results for a staged import",
          security: [{ cookieAuth: [] }],
          parameters: [
            { $ref: "#/components/parameters/ImportJobId" },
            { $ref: "#/components/parameters/Page" },
            { $ref: "#/components/parameters/PageSize" },
          ],
          responses: {
            200: successResponse("Candidate import rows loaded", ref("CandidateImportRowListData")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Import job not found"),
          },
        },
      },
      "/candidates/imports/{jobId}/commit": {
        post: {
          tags: ["Candidates"],
          summary: "Commit valid staged import rows into candidate records and queue sync jobs",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/ImportJobId" }],
          responses: {
            200: successResponse("Candidate import committed successfully", ref("CandidateImportJob")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Import job not found"),
            409: errorResponse("Import job already committed"),
          },
        },
      },
      "/candidates/{candidateId}/sync": {
        post: {
          tags: ["Candidates"],
          summary: "Queue a candidate for SIDH registration sync",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/CandidateId" }],
          responses: {
            201: successResponse("Candidate sync queued successfully", ref("SyncJob")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Candidate not found"),
            409: errorResponse("Sync already queued or not required"),
          },
        },
      },
      "/batches": {
        get: {
          tags: ["Batches"],
          summary: "List batches in the caller's visible scope",
          security: [{ cookieAuth: [] }],
          parameters: [
            { $ref: "#/components/parameters/Page" },
            { $ref: "#/components/parameters/PageSize" },
            { name: "search", in: "query", schema: { type: "string" } },
            { name: "courseId", in: "query", schema: { type: "string" } },
            { name: "schemeId", in: "query", schema: { type: "string" } },
            { name: "centerId", in: "query", schema: { type: "string" } },
            { name: "status", in: "query", schema: { type: "string", enum: ["draft", "ready", "active", "completed", "cancelled"] } },
            { name: "syncStatus", in: "query", schema: { type: "string", enum: ["not_synced", "queued", "processing", "synced", "failed", "manual_review", "cancelled"] } },
          ],
          responses: {
            200: successResponse("Batches loaded", ref("BatchListData")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
        post: {
          tags: ["Batches"],
          summary: "Create a new batch",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: true,
            content: jsonContent(ref("CreateBatchRequest")),
          },
          responses: {
            201: successResponse("Batch created successfully", ref("Batch")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            409: errorResponse("Batch code exists or candidate overlap detected"),
          },
        },
      },
      "/batches/{batchId}": {
        get: {
          tags: ["Batches"],
          summary: "Get a batch including aligned candidates and sync state",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/BatchId" }],
          responses: {
            200: successResponse("Batch loaded", ref("Batch")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Batch not found"),
          },
        },
        patch: {
          tags: ["Batches"],
          summary: "Update a batch",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/BatchId" }],
          requestBody: {
            required: true,
            content: jsonContent(ref("UpdateBatchRequest")),
          },
          responses: {
            200: successResponse("Batch updated successfully", ref("Batch")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Batch not found"),
          },
        },
      },
      "/batches/{batchId}/candidates": {
        post: {
          tags: ["Batches"],
          summary: "Add candidates to a batch",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/BatchId" }],
          requestBody: {
            required: true,
            content: jsonContent(ref("AddCandidatesToBatchRequest")),
          },
          responses: {
            200: successResponse("Candidates added to batch", ref("Batch")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Batch not found"),
            409: errorResponse("Candidate overlap or batch size limit exceeded"),
          },
        },
      },
      "/batches/{batchId}/candidates/{candidateId}": {
        delete: {
          tags: ["Batches"],
          summary: "Remove a candidate from a batch",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/BatchId" }, { $ref: "#/components/parameters/CandidateId" }],
          responses: {
            200: successResponse("Candidate removed from batch", ref("Batch")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Batch or batch candidate not found"),
          },
        },
      },
      "/batches/{batchId}/sync": {
        post: {
          tags: ["Batches"],
          summary: "Queue a batch for SIDH batch creation sync",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/BatchId" }],
          requestBody: {
            required: false,
            content: jsonContent(ref("BatchSyncRequest")),
          },
          responses: {
            200: successResponse("Batch sync queued", ref("BatchStatus")),
            400: errorResponse("Validation failed or batch is not sync-eligible"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Batch not found"),
          },
        },
      },
      "/batches/{batchId}/enrollment-sync": {
        post: {
          tags: ["Batches"],
          summary: "Queue enrollment sync for eligible candidates in a batch",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/BatchId" }],
          requestBody: {
            required: false,
            content: jsonContent(ref("EnrollmentSyncRequest")),
          },
          responses: {
            200: successResponse("Enrollment sync queued", ref("BatchStatus")),
            400: errorResponse("Batch or candidate sync prerequisites are not met"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Batch not found"),
            409: errorResponse("Remote batch is cancelled"),
          },
        },
      },
      "/batches/{batchId}/status": {
        get: {
          tags: ["Batches"],
          summary: "Get batch sync and enrollment status",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/BatchId" }],
          responses: {
            200: successResponse("Batch status loaded", ref("BatchStatus")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Batch not found"),
          },
        },
      },
      "/batches/{batchId}/assessment": {
        post: {
          tags: ["Batches"],
          summary: "Submit training, assessment, and certification details to SIDH",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/BatchId" }],
          requestBody: {
            required: true,
            content: jsonContent(ref("TrainingAssessmentSubmissionRequest")),
          },
          responses: {
            200: successResponse("Training and assessment data submitted to SIDH", ref("SidhOperationResult")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            409: errorResponse("Remote SIDH state rejected the submission"),
          },
        },
      },
      "/batches/{batchId}/certificates": {
        post: {
          tags: ["Batches"],
          summary: "Generate a SIDH certificate for a batch candidate",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/BatchId" }],
          requestBody: {
            required: true,
            content: jsonContent(ref("CertificateGenerationRequest")),
          },
          responses: {
            200: successResponse("Certificate generation requested in SIDH", ref("SidhOperationResult")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            409: errorResponse("Remote SIDH state rejected the request"),
          },
        },
        get: {
          tags: ["Batches"],
          summary: "Download a generated SIDH certificate PDF",
          security: [{ cookieAuth: [] }],
          parameters: [
            { $ref: "#/components/parameters/BatchId" },
            { name: "candidateId", in: "query", required: true, schema: { type: "string" } },
            { name: "type", in: "query", required: false, schema: { type: "string", default: "externalcertificate" } },
          ],
          responses: {
            200: {
              description: "Certificate PDF downloaded",
              content: {
                "application/pdf": {
                  schema: { type: "string", format: "binary" },
                },
              },
            },
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Certificate not found"),
          },
        },
      },
      "/batches/{batchId}/attendance-summary": {
        get: {
          tags: ["Attendance"],
          summary: "Get attendance totals and assessment readiness for a batch",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/BatchId" }],
          responses: {
            200: successResponse("Batch attendance summary loaded", ref("AttendanceSummary")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Batch not found"),
          },
        },
      },
      "/attendance/imports": {
        post: {
          tags: ["Attendance"],
          summary: "Stage an attendance workbook for row-level validation",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: true,
            content: {
              "multipart/form-data": {
                schema: ref("AttendanceImportRequest"),
              },
            },
          },
          responses: {
            201: successResponse("Attendance import staged", ref("AttendanceImportJob")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
      },
      "/attendance/imports/{jobId}": {
        get: {
          tags: ["Attendance"],
          summary: "Get a staged attendance import job",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/AttendanceImportJobId" }],
          responses: {
            200: successResponse("Attendance import loaded", ref("AttendanceImportJob")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Attendance import not found"),
          },
        },
      },
      "/attendance/imports/{jobId}/commit": {
        post: {
          tags: ["Attendance"],
          summary: "Commit a validated attendance import",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/AttendanceImportJobId" }],
          requestBody: {
            required: false,
            content: jsonContent(ref("AttendanceCommitRequest")),
          },
          responses: {
            200: successResponse("Attendance import committed", ref("AttendanceImportJob")),
            400: errorResponse("Import validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Attendance import not found"),
            409: errorResponse("Attendance records already exist for one or more rows"),
          },
        },
      },
      "/sync/jobs": {
        get: {
          tags: ["Sync Jobs"],
          summary: "List sync jobs in the caller's visible scope",
          security: [{ cookieAuth: [] }],
          parameters: [
            { $ref: "#/components/parameters/Page" },
            { $ref: "#/components/parameters/PageSize" },
            { name: "entityType", in: "query", schema: { type: "string", enum: ["candidate"] } },
            { name: "status", in: "query", schema: ref("SyncJobStatus") },
          ],
          responses: {
            200: successResponse("Sync jobs loaded", ref("SyncJobListData")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
      },
      "/sync/jobs/process": {
        post: {
          tags: ["Sync Jobs"],
          summary: "Process queued sync jobs",
          security: [{ cookieAuth: [] }],
          requestBody: {
            required: false,
            content: jsonContent(ref("ProcessSyncJobsRequest")),
          },
          responses: {
            200: successResponse("Sync jobs processed", ref("ProcessSyncJobsResult")),
            400: errorResponse("Validation failed"),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
          },
        },
      },
      "/sync/jobs/{jobId}": {
        get: {
          tags: ["Sync Jobs"],
          summary: "Get details for a specific sync job",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/SyncJobId" }],
          responses: {
            200: successResponse("Sync job loaded", ref("SyncJobDetail")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Sync job not found"),
          },
        },
      },
      "/sync/jobs/{jobId}/retry": {
        post: {
          tags: ["Sync Jobs"],
          summary: "Re-queue a failed or manual-review sync job",
          security: [{ cookieAuth: [] }],
          parameters: [{ $ref: "#/components/parameters/SyncJobId" }],
          responses: {
            200: successResponse("Sync job re-queued successfully", ref("SyncJob")),
            401: errorResponse("Authentication required"),
            403: errorResponse("Forbidden"),
            404: errorResponse("Sync job not found"),
            409: errorResponse("Sync job is currently processing"),
          },
        },
      },
      "/health": {
        get: {
          tags: ["Health"],
          summary: "Liveness probe",
          responses: {
            200: successResponse("Service is healthy", ref("HealthData")),
          },
        },
      },
      "/health/ready": {
        get: {
          tags: ["Health"],
          summary: "Readiness probe",
          responses: {
            200: successResponse("Service readiness checked", ref("ReadinessData")),
            500: errorResponse("Unexpected server error"),
          },
        },
      },
      "/openapi": {
        get: {
          tags: ["Docs"],
          summary: "Return the machine-readable OpenAPI document",
          responses: {
            200: {
              description: "OpenAPI document",
              content: jsonContent(ref("OpenApiDocument")),
            },
          },
        },
      },
    },
  };
}